[theme]
primaryColor = "#D97757"
backgroundColor = "#f3f2e7ff"
secondaryBackgroundColor = "#E3DACC"
font="serif"


[secrets]
# files = ["/home/tupham/Documents/Development/Student_Handbook/src/.streamlit/secrets.toml"]